tasks:
  - init: >
      ./.gitpod/prebuild.sh
  
  - name: Hasura
    command: docker-compose up -d
  
  - command: |
      if [[ -v $TUTORIAL_DIR ]]; then
          cd $TUTORIAL_DIR
          ls -ltr
      else     
          echo "Please specify the TUTORIAL_DIR environment variable which"
          echo "should be passed in as https://gitpod.io/#TUTORIAL_DIR=..."
          echo "See https://www.gitpod.io/docs/environment-variables"  
      fi

ports:
  - port: 5432 # postgres
    onOpen: ignore
  - port: 8080 # hasura
    onOpen: open-browser

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false